version: "3"
services:
  # service name
  web:
    # replace username/repo:tag with your name and image details
    image: 543bace/get-started:part1
    deploy:
      # Run 5 instances of that image
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        # Immediately restart containers if one fails.
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
